### PR TITLE
Rust edition 2021 & docs build fix

### LINKED ISSUE #940: Docs.rs documentation fails for 0.17
It seems that the latest successful build was for version 0.16.5

See the error on: https://docs.rs/crate/cobalt-bin/0.17.4

Here is the build log of docs.rs:

https://docs.rs/crate/cobalt-bin/0.17.0/builds/435188

### PR DESCRIPTION
**Pull request by elpiel**
This PR hopes to fix #940 
Also cleaned up a few leftovers (the macro use statements) as these were removed in the `2018` edition.

I've ran:
`cargo fix --edition`
`cargo fix --edition-idioms`

Is it possible that this fixes the docs build?
I've also checked if docs are being built for all crates in the workspace:

`cargo doc --all`
`cargo doc --all --all-features`

also double-checked with nightly:

`cargo +nightly doc --all`
`cargo +nightly doc --all --all-features`

```
elpiel@kracho:~/PROJECTS/Personal/cobalt.rs$ cargo fix --edition
note: Switching to Edition 2021 will enable the use of the version 2 feature resolver in Cargo.
This may cause some dependencies to be built with fewer features enabled than previously.
More information about the resolver changes may be found at https://doc.rust-lang.org/nightly/edition-guide/rust-2021/default-cargo-resolver.html
When building the following dependencies, the given features will no longer be used:

  bstr v0.2.17 removed features: default, lazy_static, regex-automata, unicode
  num-integer v0.1.44 removed features: i128, std
  num-traits v0.2.14 removed features: i128

    Checking cobalt-bin v0.17.4 (/home/elpiel/PROJECTS/Personal/cobalt.rs)
   Migrating src/lib.rs from 2018 edition to 2021
   Migrating tests/cli.rs from 2018 edition to 2021
   Migrating src/bin/cobalt/main.rs from 2018 edition to 2021
   Migrating tests/mod.rs from 2018 edition to 2021
    Finished dev [unoptimized + debuginfo] target(s) in 4.50s
```

### CODE REVIEW

File: src/bin/cobalt/args.rs [hunk 1]
```diff
@@ -33,7 +33,7 @@ pub fn get_config_args() -> Vec<clap::Arg<'static, 'static>> {
     .to_vec()
 }
 
-pub fn get_config(matches: &clap::ArgMatches) -> Result<cobalt_config::Config> {
+pub fn get_config(matches: &clap::ArgMatches<'_>) -> Result<cobalt_config::Config> {
```
Comment (epage) [inline src/bin/cobalt/args.rs:36]: Oh wow, I didn't realize we still had lack of lifetimes in here.

**Review by epage — APPROVED** [review]

**Comment by epage** [comment]
```
   error: failed to parse manifest at `/home/runner/work/cobalt.rs/cobalt.rs/Cargo.toml`
  
  Caused by:
    feature `edition2021` is required
  
    this Cargo does not support nightly features, but if you
    switch to nightly channel you can add
    `cargo-features = ["edition2021"]` to enable this feature
```
We need to up our MSRV. `rg --hidden MSRV` and update those to at least 1.56

**Comment by elpiel** [comment]
This is fixed now. Thanks for the hint!

Also, could you elaborate why we have:

https://github.com/cobalt-org/cobalt.rs/blob/6047852d62aa505a4dc6a82715485d465be5c596/crates/config/src/assets.rs?_pjax=%23js-repo-pjax-container%3Afirst-of-type%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%3Afirst-of-type%2C%20%5Bdata-pjax-container%5D%3Afirst-of-type#L31

What ended happening is that by default serde uses `CamelCase` for structs (as it's mentioned in the docs), however, due to this as it renames it to `snake_case`. I spend some time trying to figure out why it was not working even though I was doing it by the documentation.

**Comment by elpiel** [comment]
There seems that there are a few more clippy warnings regarding one of the macros:

```
warning: used `assert_eq!` with a literal bool
   --> src/cobalt_model/files.rs:334:13
    |
334 |             assert_eq!(files.includes_file(path::Path::new($test)), $included);
    |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: replace it with: `assert!(..)`
...
653 |         assert_includes_file!("./", ignores, "./_posts/child/_child/child.txt", false);
    |         ------------------------------------------------------------------------------- in this macro invocation
```

**Comment by epage** [comment]
Sorry, catching up now that clap 3.0.0-rc.0 is out!

> Also, could you elaborate why `SassOutputStyle` has:
> 
> https://github.com/cobalt-org/cobalt.rs/blob/6047852d62aa505a4dc6a82715485d465be5c596/crates/config/src/assets.rs#L31
> 
> What ended happening is that by default serde uses `CamelCase` for structs (as it's mentioned in the docs), however, due to this as it renames it to `snake_case`. I spend some time trying to figure out why it was not working even though I was doing it by the documentation.

We are looking at transitioning the format from CamelCase to snake_case.

Where is this causing problems?

> There seems that there are a few more clippy warnings regarding one of the macros:
> 
> ```
> warning: used `assert_eq!` with a literal bool
>    --> src/cobalt_model/files.rs:334:13
>     |
> 334 |             assert_eq!(files.includes_file(path::Path::new($test)), $included);
>     |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: replace it with: `assert!(..)`
> ...
> 653 |         assert_includes_file!("./", ignores, "./_posts/child/_child/child.txt", false);
>     |         ------------------------------------------------------------------------------- in this macro invocation
> ```

I hate this lint.  I'd recommend just doing an `#[allow(...)]` on it.  Asserts are one of the main cases I think it makes sense to do boolean equality.  In some cases, it makes the intent more clear.
